# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ikonica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelBefore = QtWidgets.QLabel(self.centralwidget)
        self.labelBefore.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.labelBefore.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelBefore.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelBefore.setText("")
        self.labelBefore.setScaledContents(True)
        self.labelBefore.setObjectName("labelBefore")
        self.horizontalLayout.addWidget(self.labelBefore)
        self.labelAfter = QtWidgets.QLabel(self.centralwidget)
        self.labelAfter.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.labelAfter.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelAfter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelAfter.setText("")
        self.labelAfter.setObjectName("labelAfter")
        self.horizontalLayout.addWidget(self.labelAfter)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(70, -1, 70, -1)
        self.horizontalLayout_2.setSpacing(150)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.workButton = QtWidgets.QPushButton(self.centralwidget)
        self.workButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        self.workButton.setFont(font)
        self.workButton.setObjectName("workButton")
        self.horizontalLayout_2.addWidget(self.workButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.naiveAlgorithm = QtWidgets.QRadioButton(self.centralwidget)
        self.naiveAlgorithm.setObjectName("naiveAlgorithm")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.naiveAlgorithm)
        self.verticalLayout_3.addWidget(self.naiveAlgorithm)
        self.dltAlgorithm = QtWidgets.QRadioButton(self.centralwidget)
        self.dltAlgorithm.setObjectName("dltAlgorithm")
        self.buttonGroup.addButton(self.dltAlgorithm)
        self.verticalLayout_3.addWidget(self.dltAlgorithm)
        self.dltNormAlgorithm = QtWidgets.QRadioButton(self.centralwidget)
        self.dltNormAlgorithm.setObjectName("dltNormAlgorithm")
        self.buttonGroup.addButton(self.dltNormAlgorithm)
        self.verticalLayout_3.addWidget(self.dltNormAlgorithm)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuProgram = QtWidgets.QMenu(self.menubar)
        self.menuProgram.setObjectName("menuProgram")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuProgram.addAction(self.actionSave)
        self.menuProgram.addAction(self.actionExit)
        self.menubar.addAction(self.menuProgram.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Računanje projektivnog preslikavanja i otklanjanje distorzije"))
        self.loadButton.setText(_translate("MainWindow", "Učitaj sliku"))
        self.workButton.setText(_translate("MainWindow", "Primeni"))
        self.label.setText(_translate("MainWindow", "Odabrane tačke:"))
        self.naiveAlgorithm.setText(_translate("MainWindow", "Naivni Algoritam"))
        self.dltAlgorithm.setText(_translate("MainWindow", "DLT algoritam"))
        self.dltNormAlgorithm.setText(_translate("MainWindow", "Normalizovani DLT algoritam"))
        self.menuProgram.setTitle(_translate("MainWindow", "Menu"))
        self.actionSave.setText(_translate("MainWindow", "Sačuvaj sliku"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Sačuvaj sliku bez distorzije"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Izlaz"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Izlaz iz programa"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
